Sources/XcodeGraph/Models/Version.swift, Tests/XcodeGraphTests/Models/VersionTests.swift
Tuist users that value when generating Xcode projects so I'm adding a public property to obtain the value
=> Add `Version.xcodeStringValue` getter to get the value to use in Xcode projects.

Sources/XcodeGraph/Models/ResourceSynthesizer.swift
Hey there 👋 
I'm trying to update https://github.com/tuist/tuist/pull/6296 PR
`stringsCatalog` enum case is needed [here](https://github.com/tuist/tuist/blob/cdb9197e43a64bf09b1b93ee867df44aa51db351/Sources/TuistLoader/Models%2BManifestMappers/ResourceSynthesizer%2BManifestMapper.swift#L46)
=> Add strings catalog parser

Sources/XcodeGraph/Graph/GraphDependency.swift, Sources/XcodeGraph/Models/Metadata/XCFrameworkMetadata.swift, Sources/XcodeGraph/Models/XCFrameworkInfoPlist.swift
Resolve #11
Since the XCFramework is a bundle support for multiple platforms, it‘s difficult to say which binary is the primary binary. It is better to keep the platform in the binary library and defer which to use when it is needed.
=> Support platform for XCFrameworkInfoPlist

Sources/XcodeGraph/Models/MetalOptions.swift, Sources/XcodeGraph/Models/RunAction.swift
This PR adds the configuration for Metal diagnostics, allowing the configuration of these fields using Tuist.
There will be three PRs in this repository: in tuist/tuist and tuist/XcodeProj.
=> Add Metal Diagnostics Options to RunAction

Sources/XcodeGraph/Models/XCFrameworkInfoPlist.swift
As @kwridan mentioned at https://github.com/tuist/tuist/pull/6414#pullrequestreview-2150602930
> In this case the issue is that encoded (raw) values of those types are incompatible.
> 
> For example, for visionOS:
> 
> XcodeGraph.Platform: has a raw value of [visionos](https://github.com/tuist/XcodeGraph/blob/main/Sources/XcodeGraph/Models/Platform.swift#L15)
> XCFrameworkInfoPlist has
> ```
> <key>SupportedPlatform</key>
> <string>xros</string> 
> ```
> As such the Platform type can't be used directly to decode SupportedPlatform and would require an intermediate step to map from the SupportedPlatform to Platform.
We can just use its own `Platform` for XCFramework.
=> Make XCFramework's Library supported platform its own.

Sources/XcodeGraph/Graph/GraphDependency.swift, Sources/XcodeGraph/Models/Metadata/XCFrameworkMetadata.swift, Sources/XcodeGraph/Models/ResourceSynthesizer.swift
I am reverting PRs that introduced breaking changes and make it impossible to update `XcodeGraph` in `tuist` as their counterpart PRs in `tuist/tuist` have not been approved and can't be merged:
- https://github.com/tuist/XcodeGraph/pull/9 -> https://github.com/tuist/tuist/pull/6296
- https://github.com/tuist/XcodeGraph/pull/12 -> https://github.com/tuist/tuist/pull/6414
=> Revert breaking changes

Sources/XcodeGraph/DependenciesGraph/DependenciesGraph.swift, Sources/XcodeGraph/Graph/GraphDependency.swift, Sources/XcodeGraph/Models/Metadata/FrameworkMetadata.swift, Sources/XcodeGraph/Models/Metadata/SystemFrameworkMetadata.swift, Sources/XcodeGraph/Models/Metadata/XCFrameworkMetadata.swift, Sources/XcodeGraph/Models/TargetDependency.swift
This is the first part of refactoring in order to support weak linking on any target in Tuist. It's either this or creating a new `TargetStatus` which doesn't seem ideal given **status** is something that can be attributed to any dependency.
=> refactor: unify status enums into one linking status

Sources/XcodeGraph/Models/Target.swift
I'm extracting the convenient static attribute, `Target.validSourceCompatibleFolderExtensions` , added in [this PR](https://github.com/tuist/tuist/pull/6198)
=> feat: add `Target.validSourceCompatibleFolderExtensions` attribute to get the list of folder extensions that are valid sources

.github/workflows/release.yml
If the changelog hash and the `git cliff` output hash don't match, we _should_ run a release, not skip it.
=> ci: fix deteremining whether a release should be run

Package.resolved, Sources/XcodeGraph/Graph/GraphDependency.swift, Sources/XcodeGraph/Models/TargetDependency.swift
Support setting the linking status to `target` and `project` dependencies.
See the tuist PR for more context: https://github.com/tuist/tuist/pull/6731
=> feat: add linking status to target and project

Package.resolved, Sources/XcodeGraph/Models/Settings.swift
When working on https://github.com/tuist/tuist/pull/6757, I noticed the `Settings.with` mapper is missing a `baseDebug` property.
=> fix: missing baseDebug in Settings.with

Sources/XcodeGraph/Models/Target.swift, Tests/XcodeGraphTests/Models/TargetTests.swift
As per title, this is needed to compile [capnproto](https://github.com/capnproto/capnproto) as a dependency with Tuist.
=> fix: add c++ to valid source extensions

Package.resolved, Sources/XcodeGraph/Models/TargetDependency.swift
Adds `.none` type to `LinkingStatus` to indicate that no linking should be done on a target dependency.
This is a first step to solve https://github.com/tuist/tuist/issues/6751
Unblocks https://github.com/tuist/tuist/pull/6838
=> feat: add .none linking status

Sources/XcodeGraph/Models/BuildAction.swift
This PR exposes a `buildImplicitDependencies` property on `BuildAction` in order to enable the possibility in tuist to control the `Find Implicit Dependencies` in build actions. I used `true` as the default to not break any upstream changes since it is the default for Xcode as well. 
The reason why I think it's a useful addition is that in the official tuist documentation it is recommended to disable this setting(https://docs.tuist.io/en/guides/develop/projects/cost-of-convenience#find-implicit-dependencies-in-schemes) but there seems to be no way through tuist to do it.
Let me know what you think about this addition. In case you like the idea I would also drive the implementation in the tuist CLI afterwards.
=> feat: expose findImplicitDependencies property on BuildAction

Sources/XcodeGraph/Graph/GraphDependency.swift, Sources/XcodeGraph/Models/TargetDependency.swift
Change for https://github.com/tuist/tuist/issues/6683
This pull request introduces new types of the package dependency, which are required for further development of the feature to add SPM package product to Embed Frameworks.
=> feat: add new types for embeddable SPM package 

.github/workflows/XcodeGraph.yml, .github/workflows/cache.yml, .github/workflows/release.yml, .mise.toml, Sources/XcodeGraph/Graph/GraphTarget.swift, Sources/XcodeGraph/Models/Project.swift
As part of [debugging this issue](https://github.com/tuist/tuist/issues/7018), which we couldn't reproduce consistently (e.g., its behavior changes throughout terminal types), @fortmarek and I had the idea of skipping the hashing of external dependencies, since their hash can be obtained from the lock file. 
To achieve this, I'm introducing a new attribute, `Project.type`, which supersedes `Project.external`. This attribute can then include a hash when declaring a projects external. The hashing logic can then consider this to skip the hashing altogether. Thanks to this, we'll improve our performance. 
> [!NOTE]
> This doesn't mitigate the issue, but since it always happens with the same external dependency, we won't run into it.
=> [feat] Supersede `Project.external` with `Project.type` 

Sources/XcodeGraph/Models/Project.swift
When we use `Project.test()`, it should automatically use the non-deprecated method. We shouldn't require specifying `projectType` as that defeats the purpose of `test()` where you specify only properties you need in a specific test.
The only time we should give a deprecation warning is when the consumers explicitly use the `isExternal` in the `Project.test()` invocation.
=> fix: invocation of Project.test() without specified ProjectType should use new method

Sources/XcodeGraph/Models/Project.swift
I'm making `Project.type` non-optional. If `isExternal` init is used, we derive the value.
=> fix: make Project.type non-optional

Sources/XcodeGraph/Extensions/SettingsDictionary+Extras.swift, Sources/XcodeGraph/Models/Settings.swift, Tests/XcodeGraphTests/Extensions/SettingsDictionary+ExtrasTests.swift
If the `SettingsDictionary` does _not_ include a given key and we run `overlay(with: ["SETTINGS_KEY": "value"], for: .visionOS)`, the resulting settings should still include the platform specifiers:
```
[
"SETTINGS_KEY[sdk=xros*]": "value"
]
```
=> fix: overlay platform-specific settings when the value does not exist

Sources/XcodeGraph/Models/Target.swift
Needed for tuist/tuist#7006
`Target.supportsResources` returns `true` if `Target.product == .staticFramework`.
=> feat: supportsResources returns true if product is staticFramework

Package.swift, Sources/XcodeGraph/Models/Metadata/TargetMetadata.swift, Sources/XcodeGraph/Models/Target.swift, Sources/XcodeGraph/Models/TargetType.swift
Replaces the `isLocal` boolean property with a new `TargetType` enum that better represents whether a target is local or remote. This change provides more explicit semantics around target types and removes the need for documentation comments explaining the boolean's meaning.
=> fix: replace `TargetMetadata.isLocal` with `Target.type` enum

Sources/XcodeGraph/Models/TestableTarget.swift, Tests/XcodeGraphTests/Models/TestableTargetTests.swift
Adding `TestableTarget.parallelization` property that was added in `XcodeProj` in: https://github.com/tuist/XcodeProj/pull/871
For more context, see also the Tuist PR: https://github.com/tuist/tuist/pull/7200
=> feat: add TestableTarget.parallelization property

Sources/XcodeGraph/Models/Target.swift
See the counterpart PR at `tuist/tuist` for the reasoning: https://github.com/tuist/tuist/pull/7232
=> fix: revert staticFramework supporting resources

Sources/XcodeGraph/Graph/Graph.swift
This method was made accidentally internal in https://github.com/tuist/XcodeGraph/pull/87 and it breaks testing code in `tuist/tuist` on update of `XcodeGraph`. cc @ajkolean
=> fix: make Graph test factory public

Sources/XcodeGraphMapper/Mappers/Phases/PBXFrameworksBuildPhaseMapper.swift, Tests/XcodeGraphMapperTests/MapperTests/Phases/PBXFrameworksBuildPhaseMapperTests.swift
When mapping framework dependencies, we were assuming that a framework would be referred by a full path. However, that's not the case when a target depends on a different framework target. In those cases, frameworks are referred to by their relative path and their `sourceTree` is `buildProductsDir`.
=> fix: missing framework target dependency

Sources/XcodeGraphMapper/Mappers/Graph/XcodeGraphMapper.swift, Sources/XcodeGraphMapper/Mappers/Schemes/XCSchemeMapper.swift, Tests/XcodeGraphMapperTests/MapperTests/Graph/GraphMapperTests.swift, Tests/XcodeGraphMapperTests/MapperTests/Schemes/XCSchemeMapperTests.swift
Dependency and project paths currently include the `.xcodeproj` component, such as `some-path/project/Project.xcodeproj`. However, in `tuist/tuist`, project paths usually reference to `some-path/project` without the `Project.xcodeproj`. This PR aligns the mapper with this convention.
When the path to `.xcodeproj` is needed, we can still use the `xcodeProjPath` of `Project`.
cc @ajkolean
=> fix: remove .xcodeproj path component from most paths

Package.resolved, Sources/XcodeGraphMapper/Mappers/Project/PBXProjectMapper.swift
When I ran `XcodeGraphMapper` on `tuist/tuist`, it was _very_ slow. Mapping projects concurrently improves things a ton and thanks to the functional mapper approach, doing this is a couple of line. We can consider running more granular mappers if the performance would be still an issue for large projects.
=> fix: improve performance of XcodeGraphMapper

Package.resolved, Sources/XcodeGraphMapper/Mappers/Graph/XcodeGraphMapper.swift, Sources/XcodeGraphMapper/Mappers/Phases/PBXFrameworksBuildPhaseMapper.swift, Sources/XcodeGraphMapper/Mappers/Project/PBXProjectMapper.swift, Sources/XcodeGraphMapper/Mappers/Targets/PBXTargetMapper.swift, Sources/XcodeGraphMapper/Utilities/ProjectNativeTarget.swift, Tests/XcodeGraphMapperTests/MapperTests/Phases/PBXFrameworksBuildPhaseMapperTests.swift, Tests/XcodeGraphMapperTests/MapperTests/Project/PBXProjectMapperTests.swift, Tests/XcodeGraphMapperTests/MapperTests/Target/PBXTargetMapperTests.swift
When mapping a target framework from a different project, we would incorrectly default to a `.target` framework dependency. To fix this, we are constructing a map of target names to a `ProjectNativeTarget` – a helper struct that contains the necessary models we need to return a `TargetDependency.project`.
Additionally, we are now reading `buildSettings` of a given target framework to derive the `linkingStatus`.
=> fix: correctly map project target framework

Package.resolved, Sources/XcodeGraphMapper/Mappers/Graph/XcodeGraphMapper.swift, Sources/XcodeGraphMapper/Mappers/Targets/TargetDependency+GraphMapping.swift, Tests/XcodeGraphMapperTests/MapperTests/Target/TargetDependencyExtensionsTests.swift
I am not 100 % sure why we were mapping project target dependencies to cases such as `.framework`, however, this breaks some of the logic in `tuist`. Dependency to cases like `.framework` are only when those products are _prebuilt_. That's not the case for project target dependencies.
Additionally, this simplifies the mapping logic a bit.
=> fix: do not map project target dependency to an underlying type

Package.resolved, Sources/XcodeGraphMapper/Mappers/Targets/PBXTarget+BuildSettings.swift, Sources/XcodeGraphMapper/Mappers/Targets/PBXTargetMapper.swift, Tests/XcodeGraphMapperTests/MapperTests/Target/PBXTargetMapperTests.swift
When mapping the `Info.plist` file, the `INFOPLIST_FILE` variable can contain variables like `SRCROOT` or `PROJECT_DIR`. To be able to read the `Info.plist`, we need to expand these to get an absolute path.
=> fix: mapping Info.plist when referenced with a SRCROOT or PROJECT_DIR variable

Sources/XcodeGraphMapper/Mappers/Project/PBXProjectMapper.swift, Sources/XcodeGraphMapper/Mappers/Schemes/XCSchemeMapper.swift, Sources/XcodeGraphMapper/Mappers/Schemes/XCTestPlan.swift, Sources/XcodeGraphMapper/Mappers/Workspace/XCWorkspaceMapper.swift, Tests/XcodeGraphMapperTests/MapperTests/Schemes/XCSchemeMapperTests.swift, Tests/XcodeGraphMapperTests/MapperTests/Target/PBXTargetMapperTests.swift
When mapping `XCScheme`, we would not try to map test plans at all. This PR fixes this omission.
=> fix: map test plans

Sources/XcodeGraph/Models/Target.swift
See the PR in tuist for more context: https://github.com/tuist/tuist/pull/7323
=> fix: model as resource instead of source

Package.swift, Sources/XcodeGraph/Models/Target.swift, Sources/XcodeGraph/Models/Version.swift, Sources/XcodeGraph/PackageInfo.swift, Sources/XcodeGraphMapper/Mappers/Graph/XcodeGraphMapper.swift, Sources/XcodeGraphMapper/Mappers/Packages/PackageMapper.swift, Sources/XcodeGraphMapper/Mappers/Packages/XCPackageMapper.swift, Sources/XcodeGraphMapper/Mappers/Project/PBXProjectMapper.swift, Sources/XcodeGraphMapper/Mappers/Schemes/XCSchemeMapper.swift, Sources/XcodeGraphMapper/Mappers/Targets/PBXTargetMapper.swift, Sources/XcodeGraphMapper/Mappers/Workspace/XCWorkspaceMapper.swift, Sources/XcodeGraphMapper/Utilities/PackageInfoLoader.swift, Tests/XcodeGraphMapperTests/MapperTests/Graph/XcodeGraphMapperTests.swift, Tests/XcodeGraphMapperTests/MapperTests/Package/PackageMapperTests.swift, Tests/XcodeGraphMapperTests/MapperTests/Project/PBXProjectMapperTests.swift, Tests/XcodeGraphMapperTests/MapperTests/Schemes/XCSchemeMapperTests.swift, Tests/XcodeGraphMapperTests/MapperTests/Target/PBXTargetMapperTests.swift, Tests/XcodeGraphTests/Models/PackageInfoTests.swift
This PR adds new functionality to `XcodeGraphMapper` that converts local package targets referenced by the Xcode project to Xcode targets. This translation is lossy in some cases – in other words, the `Target` representation is not a perfect representation of the package target.
However, it's been the most straightforward way to unlock selective testing or `tuist graph` to be usable also for local packages.
The alternative to mapping a SwiftPM target to an Xcode target was to modify `Graph` to not only hold `projects`, but also `localPackages`. The models in the `localPackages` property would then be idiomatic to SwiftPM. However, in `tuist/tuist`, this would mean a _ton_ of refactoring to bring selective testing and graph for that part of the graph – as the `graphTraverser` currently …
=> feat: add mapping of local packages

Package.resolved, Package.swift, Sources/XcodeGraphMapper/Mappers/Phases/PBXCopyFilesBuildPhaseMapper.swift, Sources/XcodeGraphMapper/Mappers/Project/PBXProjectMapper.swift, Sources/XcodeGraphMapper/Mappers/Targets/PBXTarget+GraphMapping.swift, Sources/XcodeGraphMapper/Mappers/Targets/PBXTargetMapper.swift, Tests/XcodeGraphMapperTests/MapperTests/Phases/PBXCopyFilesBuildPhaseMapperTests.swift, Tests/XcodeGraphMapperTests/MapperTests/Target/PBXTargetMapperTests.swift
Adds support for correctly mapping build phase file references from synchronized groups.
The support for the `PBXFileSystemSynchronizedGroupBuildPhaseMembershipExceptionSet` in `XcodeProj` is added via https://github.com/tuist/XcodeProj/pull/894
=> fix: mapping build phases with exceptions

Sources/XcodeGraph/Models/XCFrameworkInfoPlist.swift, Tests/XcodeGraphTests/Models/XCFrameworkInfoPlistTests.swift
This PR fixes the encoding of `XCFrameworkInfoPlist`. 
When encoding the `XcodeGraph.Graph` type it appears to miss the `platform` property. This leads to decoding Issues when decoding the data again.
=> fix: encoding of XCFrameworkInfoPlist

Sources/XcodeGraphMapper/Mappers/Phases/PBXResourcesBuildPhaseMapper.swift, Sources/XcodeGraphMapper/Mappers/Targets/PBXTargetMapper.swift, Tests/XcodeGraphMapperTests/MapperTests/Phases/PBXResourcesBuildPhaseMapperTests.swift, Tests/XcodeGraphMapperTests/MapperTests/Target/PBXTargetMapperTests.swift
This PR is very similar to https://github.com/tuist/XcodeGraph/pull/110 but for resources. In a resources build phase, we can reference a target bundle that's in build products directory. In that case, instead of trying to resolve a full path, we should return either `.target` or `.project` dependency.
=> fix: mapping resource build phase with bundle targets

Sources/XcodeGraph/Models/Version.swift, Tests/XcodeGraphTests/Models/VersionTests.swift
This PR fixes the decoding of the `Version` type.
While the encoding of this type was using a single value container no explicit decoding init was specified. This led to the fact the default synthesised decoding initialiser is used. But this one will expect the full fletched object to be encoded. This leads to decoding errors, like the following: 
```
Error: typeMismatch(Swift.Dictionary<Swift.String, Any>, Swift.DecodingError.Context(codingPath: [
CodingKeys(stringValue:"projects", intValue: nil),
_CodingKey(stringValue: "Index 7", intValue: 7),
CodingKeys(stringValue: "lastUpgradeCheck", intValue: nil)
],
debugDescription: "Expected to decode Dictionary<String, Any> but found a string instead.",
underlyingError: nil)
)
```
This PR now implements a custom decoding initialiser matching …
=> fix: fix Version decoding

Sources/XcodeGraph/Extensions/SettingsDictionary+Extras.swift, Tests/XcodeGraphTests/Extensions/SettingsDictionary+ExtrasTests.swift
When combining two settings values that are both arrays, we can easily introduce duplicate values. In extreme cases, this leads to thousands of duplicates, causing Xcode to freeze.
=> fix: duplicated values in build settings

Sources/XcodeGraphMapper/Mappers/Phases/PBXFrameworksBuildPhaseMapper.swift, Tests/XcodeGraphMapperTests/MapperTests/Phases/PBXFrameworksBuildPhaseMapperTests.swift
When mapping SDKs (such as `Foundation.framework`) in the frameworks build phase, instead of trying to resolve a full path, which would fail, we should return the `TargetDependency.sdk` case.
=> fix: mapping SDK frameworks

Sources/XcodeGraphMapper/Mappers/Graph/XcodeGraphMapper.swift, Sources/XcodeGraphMapper/Utilities/ProjectNativeTarget.swift, Tests/XcodeGraphMapperTests/MapperTests/Graph/XcodeGraphMapperTests.swift
When finding frameworks across all native targets using the `projectNativeTargets` parameter, we need to try match the sanitized variant as that's how a framework target is referenced in the frameworks build phase.
For example, an `App-With-Dash` target will be included in the frameworks build phase as `App_With_Dash`.
=> fix: framework not found when name needs to be sanitized

Package.resolved, Sources/XcodeGraph/Models/TargetScript.swift, Sources/XcodeGraphMapper/Mappers/Phases/PBXScriptsBuildPhaseMapper.swift, Tests/XcodeGraphMapperTests/MapperTests/Phases/PBXScriptsBuildPhaseMapperTests.swift
File list paths in build phases can be dynamic when referenced with build variables, such as `${PODS_ROOT}/Target Support Files/Pods-App/Pods-App-frameworks-${CONFIGURATION}-input-files.xcfilelist` in the case of Cocoapods projects.
We should align `inputFileListPaths` and `outputFileListPaths` with `inputPaths` and `outputPaths` types which are `[String]`.
This is minor breaking change.
I've also considered preserving the absolute paths and evaluating the build settings – but when the file list is referenced with a configuration-specific build setting variable, we could never actually resolve the right path.
Changing the type to `[String]` feels like the only correct way of going about this.
=> feat: support dynamic file list paths

Sources/XcodeGraph/Extensions/SettingsDictionary+Extras.swift, Tests/XcodeGraphTests/Extensions/SettingsDictionary+ExtrasTests.swift
This reverts commit db41514648f80f90882a2afee3daad8bb573c235.
We can't deduplicate all build settings when they are combined. In some cases, some values _have_ to be duplicated, such as each Swift C-related flag needs to be prefixed with its own `-Xcc`.
=> revert: duplicated values in build settings

Package.resolved, Sources/XcodeGraphMapper/Mappers/Phases/PBXCopyFilesBuildPhaseMapper.swift, Sources/XcodeGraphMapper/Mappers/Phases/PBXFrameworksBuildPhaseMapper.swift, Tests/XcodeGraphMapperTests/MapperTests/Graph/XcodeGraphMapperTests.swift
As raised [here](https://community.tuist.dev/t/selective-testing-for-non-generated-projects/381/7?u=marekfort), the current error message for when a `PBXBuildFile.file` reference is not found doesn't provide any extra details for what's missing.
Current error message:
```
Missing `PBXBuildFile.file` reference.
```
New error message example:
```
Missing 'PBXBuildFile.file' reference for F806E10B2D54DD7C0058A673 id. Make sure an element with that id is present in the /Users/marekfort/Developer/tuist/fixtures/xcode_project_with_tests/App.xcodeproj/project.pbxproj file
```
The error message is relatively low-level, but I'd rather go low-level than provide a high-level error message that doesn't provide any insights into what the error might be.
=> feat: improve error message when PBXBuildFile.file reference is not found

Package.resolved, Sources/XcodeGraphMapper/Mappers/Project/PBXProjectMapper.swift, Sources/XcodeGraphMapper/Mappers/Targets/PBXTargetMapper.swift, Tests/XcodeGraphMapperTests/MapperTests/Target/PBXTargetMapperTests.swift
As [reported](https://community.tuist.dev/t/selective-testing-for-non-generated-projects/381/9?u=marekfort) by @KaiOelfke, mapping aggregate targets is failing as we're assuming they have some properties that only `PBXNativeTarget`s have, such as a list of supported destinations.
Since `XcodeGraph` doesn't currently support aggregate targets, we will, for now, skip mapping these completely.
I flagged an [issue](https://github.com/tuist/XcodeGraph/issues/141) to eventually add support for these targets, so the conversion from XcodeProj to XcodeGraph is not lossy.
=> fix: skip mapping aggregate targets

Package.resolved, Sources/XcodeGraphMapper/Mappers/Graph/XcodeGraphMapper.swift, Tests/XcodeGraphMapperTests/MapperTests/Graph/XcodeGraphMapperTests.swift, Tests/XcodeGraphMapperTests/TestData/PBXNativeTarget+TestData.swift
Resolves issue raised [here](https://community.tuist.dev/t/selective-testing-for-non-generated-projects/381/14).
In Pods projects, the resource bundle added as a dependency uses the product name. However, the target name can be different such`Alamofire-iOS-Alamofire` bundle's product name is `Alamofire`. When creating the `projectNativeTargets` map, we use the product name as the key, so we don't [throw here](https://github.com/tuist/XcodeGraph/blob/main/Sources/XcodeGraphMapper/Mappers/Phases/PBXResourcesBuildPhaseMapper.swift#L107).
Note this can cause a mismatch when the targets have a different name but the same product name. I couldn't figure out a good way to match the bundle product name with a specific target when there are multiple targets with the same product. I'd think this is …
=> fix: mapping fails when bundle product name differs from target name

Sources/XcodeGraphMapper/Mappers/Graph/XcodeGraphMapper.swift, Tests/XcodeGraphMapperTests/MapperTests/Graph/XcodeGraphMapperTests.swift
This PR fixes a small issue in the recursive build up on child projects in a XCWorkpace. When running `extractProjectPaths` on the `XcodeGraphMapper` and encountering a `.group` the groups location was not appended to the projects path. This results into incorrect paths for any child projects in the graph.
An example `contents.xcworkspacedata` which contains nested groups: 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Workspace
version = "1.0">
<FileRef
location = "group:MyProject/MyProject.xcodeproj">
</FileRef>
<Group
location = "group:Modules"
name = "Modules">
<FileRef
location = "group:ModuleA/ModuleA.xcodeproj">
</FileRef>
</Group>
</Workspace>
```
With the current implementation, the `ModuleA` project path ends up to be `<root>/ModuleA` even though it is part of a `Modules` …
=> fix: fix project paths respecting nested projects

Sources/XcodeGraph/Models/Target.swift
Tuist was previously using `Target.supportsSources` to check whether a target supports or not sources, but it turns out it's not just a binary decision based on the product. For instance, `.metal` files can be added as sources to bundle targets.
This PR deprecates `Target.supportsSources` in favor of a more flexible alternative, `Target.validatedSources`.
=> feat: Add `Target.validatedSources` to filter the sources that are invalid

Package.resolved, Package.swift, Sources/XcodeGraph/DependenciesGraph/DependenciesGraph.swift, Sources/XcodeGraph/Graph/GraphDependency.swift, Sources/XcodeGraph/Models/Metadata/XCFrameworkMetadata.swift, Sources/XcodeGraph/Models/TargetDependency.swift, Sources/XcodeGraphMapper/Extensions/TargetDependency+Extensions.swift, Sources/XcodeGraphMapper/Mappers/Phases/PBXFrameworksBuildPhaseMapper.swift, Sources/XcodeGraphMapper/Mappers/Targets/PBXTargetDependencyMapper.swift, Sources/XcodeGraphMapper/Mappers/Targets/TargetDependency+GraphMapping.swift, Sources/XcodeGraphMapper/Utilities/PathDependencyMapper.swift, Sources/XcodeMetadata/Providers/XCFrameworkMetadataProvider.swift, Tests/XcodeGraphMapperTests/MapperTests/Target/TargetDependencyExtensionsTests.swift, Tests/XcodeGraphTests/Models/TargetDependencyTests.swift, Tests/XcodeMetadataTests/XCFrameworkMetadataProviderTests.swift
Support XCFrameworks expectedSignature property, and add the expected expectedSignature to the target dependency, to be verified against the actual signature.
More about XCFramework's siganture:
https://developer.apple.com/documentation/Xcode/verifying-the-origin-of-your-xcframeworks
=> feat(PBXFileReference): support XCFramework expectedSignature property

Sources/XcodeGraph/Models/Plist.swift, Tests/XcodeGraphTests/Models/InfoPlistTests.swift
This PR implements the support for variable InfoPlist file paths for build settings that mirrors the existing API for setting variable entitlements file paths. The issue has been described in detail here: https://github.com/tuist/tuist/issues/6727
This change is needed to unblock https://github.com/tuist/tuist/pull/7404
=> feat: add support for defining Info.plist files using a variable

Package.resolved, Sources/XcodeGraph/Models/BuildableFolderException.swift
By default they have the project access level so we need this to allow users to control the access level.
=> feat: include `publicHeaders` and `privateHeaders` in buildable folder exceptions
